#!/usr/bin/env bash
#write a Bash script that configures a new Ubuntu machine to respect above requirements
sudo apt update
apt-get -y upgrade
apt-get -y install nginx

ufw allow 'Nginx HTTP'
echo "Hello World" > /var/www/html/index.nginx-debian.html
service nginx restart
