#!/usr/bin/env bash
#Install nginx on
apt-get -y update
apt-get -y install nginx

ufw allow 'Nginx HTTP'

echo "Hello World" > /var/www/html/index.nginx-debian.html
sed -i '/listen 80 default_server;/a \\tlocation /redirect_me { rewrite ^ https://www.youtube.com/watch?v=QH2-TGUlwu4/ permanent; }' /etc/nginx/sites-available/default

echo "Ceci n'est pas une page" > /var/www/html/404.html
sed -i '/listen 80 default_server;/a \\terror_page 404 /404.html;\n\tlocation = 404.html {\n\t\troot /var/www/html;\n\t\tinternal;\n\t}\n' /etc/nginx/sites-available/default

service nginx restart