#!/usr/bin/env bash
# Install and configure HAproxy on your lb-01 server

apt-get update
apt-get -y install haproxy


# frontend myfrontend
#   bind *:80
#   mode http
#   default_backend web_servers

# backend web_servers
#   balance roundrobin
#   server web1 50.19.193.215:80 check
#   server web2 54.227.31.122:80 check

sed -i "$ a frontend myfrontend\n\tbind *:80\n\tmode http\n\tdefault_backend web_servers\n" /etc/haproxy/haproxy.cfg
sed -i "$ a backend web_servers\n\tbalance roundrobin\n\tserver web1 50.19.193.215:80 check\n\tserver web2 54.227.31.122:80 check" /etc/haproxy/haproxy.cfg

sudo service haproxy start
