#!/usr/bin/env bash
# Script that generates a MySQL dump and
# creates a compressed archive out of it.
# MySQLのダンプを生成し、そこから圧縮アーカイブを作成するBashスクリプトを書く
# tar -czvf アーカイブ.tgz 対象ファイル（ファイルのアーカイブを作成しgzip形式で圧縮する）
# tar -xzvf アーカイブ.tgz（gzipで圧縮されたアーカイブを展開する）

# "c" : 新しいアーカイブを作成する
# "z" : アーカイブをgzip形式で圧縮する、gzip形式で圧縮されたアーカイブを展開する（拡張子は「.tar.gz」または「.tgz」）
# "v" : 処理したファイルを詳しく出力する
# "f" : アーカイブファイル名を指定する
# https://www.digitalocean.com/community/tutorials/how-to-import-and-export-databases-and-reset-a-root-password-in-mysql

# Export all databases to backup.sql //mysqldump -u [username] -p [database name] > [database name].sql
mysqldump -u root -p"$1" --all-databases > backup.sql
tar -czvf "$(date +%d-%m-%Y).tar.gz" backup.sql
