#!/usr/bin/env bash
# This script is displaying "Best School" 9 times and "Hi!"
i=0
while [ $i -lt 10 ]
do
  if  [ $i -eq 8 ]; then
    echo "Hi"
  else
    echo "Best School"
  fi
  i=$(( i + 1 ))
done
