#!/usr/bin/env bash
# This script is displaying "Best School" 10 times
i=0
while (( i < 25 ))
do
    echo "Hour: $i"
    j=0
    if (( j < 24 )); then
        while (( j < 59 ))
        do
            j=$(( j + 1 ))
            echo "$j"
        done
    fi
    i=$(( i + 1 ))
done
