#!/usr/bin/env bash
# This script is displaying "Best School" 10 times
i=0
while [ $i -lt 25 ]
do
    echo "Hour: $i"
    j=0
    if [ $i -ne 24 ]; then
        while [ $j -lt 59 ]
        do
            j=$(( j + 1 ))
            echo "$j"
        done
    fi
    i=$(( i + 1 ))
done
