#!/usr/bin/env bash
# script that gives you information about the school file
touch school
if [ -f school ]; then
    echo "school file exists"
        if [ ! -s $school ]; then
            echo "school file is empty"
        elif [ -s $school ]; then
            echo "school file is not empty"
        elif [ -f $school ]; then
            echo "school is a regular file"
        elif [ ! -f $school ]; then
else
    echo "school file does not exist"
fi
