#!/usr/bin/env bash
#Config of firewall

# install ufw if not yet
sudo apt install ufw
# not accept receiving
sudo ufw default deny incoming
# accept sending
sudo ufw default allow outgoing

# sudo ufw allow 22
sudo ufw allow ssh
# sudo ufw allow 80
sudo ufw allow http
# sudo ufw allow 443
sudo ufw allow https
# active ufw
sudo ufw enable
