#!/usr/bin/env bash
# change localhost from 127.0.0.1 to 127.0.0.2 and facebook.com from 157.240.11.35 to 8.8.8.8
cp /etc/hosts ~/hosts.new
sed -i "s/127.0.0.1/127.0.0.2/g" ~/hosts.new
sed -i "1i8.8.8.8 facebook.com" ~/hosts.new
cp -f ~/hosts.new /etc/hosts
